# Generated by Django 4.1.6 on 2023-02-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='статья от 2023-02-09 02:23:27.533607', max_length=64),
        ),
    ]
