# Generated by Django 4.1.5 on 2023-01-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='статья от 2023-01-17 12:44:40.310233', max_length=64),
        ),
    ]
