# Generated by Django 4.1.5 on 2023-01-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='статья от 2023-01-17 12:50:08.293590', max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default='AT', max_length=2),
        ),
    ]
