# Generated by Django 4.1.5 on 2023-01-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_post_title_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='статья от 2023-01-17 13:28:14.819308', max_length=64),
        ),
    ]
