# Generated by Django 4.1.5 on 2023-01-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='статья от 2023-01-17 19:29:38.435662', max_length=64),
        ),
    ]
