# Generated by Django 4.1.5 on 2023-01-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='статья от 2023-01-19 09:56:52.931316', max_length=64),
        ),
    ]
