# Generated by Django 4.1.5 on 2023-01-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_post_title_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='статья от 2023-01-25 13:02:05.318631', max_length=64),
        ),
    ]
